print("*" * 39)
print("THIEP MOI")
print('Than moi ban: "Nguyen Minh Ngoc"')
print("Toi du le sinh nhat cua minh")
print("Vao luc 19h ngay 20/10/2016")
print("Tai: 05/42 Dien Bien Phu – TP. HCM")
print("Rat mong duoc don tiep!")
print("Ho Le Thu")
print("*" * 39)
